_target_: src.models.modelmodule.PoseNetModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0012
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.CustomMaskRCNN.get_maskrcnn_with_backbone
  pretrained: true
  num_classes: 8

# compile model for faster training with pytorch 2.0
compile: false
